























.build/leonardo/HX711/HX711.o : lib/HX711/HX711.cpp
	@echo HX711/HX711.cpp
	@mkdir -p .build/leonardo/HX711
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c lib/HX711/HX711.cpp
include .build/leonardo/HX711/HX711.d



.build/leonardo/HX711/libHX711.a : .build/leonardo/HX711/HX711.o
	@echo Linking libHX711.a
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^







.build/leonardo/arduino/WInterrupts.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
	@echo arduino/WInterrupts.c
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
include .build/leonardo/arduino/WInterrupts.d

.build/leonardo/arduino/wiring.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
	@echo arduino/wiring.c
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
include .build/leonardo/arduino/wiring.d

.build/leonardo/arduino/wiring_shift.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
	@echo arduino/wiring_shift.c
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
include .build/leonardo/arduino/wiring_shift.d

.build/leonardo/arduino/hooks.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
	@echo arduino/hooks.c
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
include .build/leonardo/arduino/hooks.d

.build/leonardo/arduino/wiring_pulse.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
	@echo arduino/wiring_pulse.c
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
include .build/leonardo/arduino/wiring_pulse.d

.build/leonardo/arduino/wiring_analog.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
	@echo arduino/wiring_analog.c
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
include .build/leonardo/arduino/wiring_analog.d

.build/leonardo/arduino/wiring_digital.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
	@echo arduino/wiring_digital.c
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
include .build/leonardo/arduino/wiring_digital.d






.build/leonardo/arduino/CDC.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
	@echo arduino/CDC.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
include .build/leonardo/arduino/CDC.d

.build/leonardo/arduino/main.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
	@echo arduino/main.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
include .build/leonardo/arduino/main.d

.build/leonardo/arduino/new.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
	@echo arduino/new.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
include .build/leonardo/arduino/new.d

.build/leonardo/arduino/WString.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
	@echo arduino/WString.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
include .build/leonardo/arduino/WString.d

.build/leonardo/arduino/IPAddress.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
	@echo arduino/IPAddress.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
include .build/leonardo/arduino/IPAddress.d

.build/leonardo/arduino/HardwareSerial1.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
	@echo arduino/HardwareSerial1.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
include .build/leonardo/arduino/HardwareSerial1.d

.build/leonardo/arduino/Print.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
	@echo arduino/Print.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
include .build/leonardo/arduino/Print.d

.build/leonardo/arduino/HardwareSerial0.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
	@echo arduino/HardwareSerial0.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
include .build/leonardo/arduino/HardwareSerial0.d

.build/leonardo/arduino/HID.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp
	@echo arduino/HID.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp
include .build/leonardo/arduino/HID.d

.build/leonardo/arduino/WMath.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
	@echo arduino/WMath.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
include .build/leonardo/arduino/WMath.d

.build/leonardo/arduino/Tone.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
	@echo arduino/Tone.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
include .build/leonardo/arduino/Tone.d

.build/leonardo/arduino/HardwareSerial.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
	@echo arduino/HardwareSerial.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
include .build/leonardo/arduino/HardwareSerial.d

.build/leonardo/arduino/abi.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
	@echo arduino/abi.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
include .build/leonardo/arduino/abi.d

.build/leonardo/arduino/USBCore.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
	@echo arduino/USBCore.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
include .build/leonardo/arduino/USBCore.d

.build/leonardo/arduino/HardwareSerial3.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
	@echo arduino/HardwareSerial3.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
include .build/leonardo/arduino/HardwareSerial3.d

.build/leonardo/arduino/HardwareSerial2.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
	@echo arduino/HardwareSerial2.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
include .build/leonardo/arduino/HardwareSerial2.d

.build/leonardo/arduino/Stream.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
	@echo arduino/Stream.cpp
	@mkdir -p .build/leonardo/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
include .build/leonardo/arduino/Stream.d



.build/leonardo/arduino/libarduino.a : .build/leonardo/arduino/WInterrupts.o .build/leonardo/arduino/wiring.o .build/leonardo/arduino/wiring_shift.o .build/leonardo/arduino/hooks.o .build/leonardo/arduino/wiring_pulse.o .build/leonardo/arduino/wiring_analog.o .build/leonardo/arduino/wiring_digital.o .build/leonardo/arduino/CDC.o .build/leonardo/arduino/main.o .build/leonardo/arduino/new.o .build/leonardo/arduino/WString.o .build/leonardo/arduino/IPAddress.o .build/leonardo/arduino/HardwareSerial1.o .build/leonardo/arduino/Print.o .build/leonardo/arduino/HardwareSerial0.o .build/leonardo/arduino/HID.o .build/leonardo/arduino/WMath.o .build/leonardo/arduino/Tone.o .build/leonardo/arduino/HardwareSerial.o .build/leonardo/arduino/abi.o .build/leonardo/arduino/USBCore.o .build/leonardo/arduino/HardwareSerial3.o .build/leonardo/arduino/HardwareSerial2.o .build/leonardo/arduino/Stream.o
	@echo Linking libarduino.a
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build/leonardo/src/weight.o : .build/leonardo/src/weight.cpp
	@echo src/weight.cpp
	@mkdir -p .build/leonardo/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=164 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/avr/variants/leonardo -Ilib/HX711 -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -fno-exceptions -iquote src  -o $@ -c .build/leonardo/src/weight.cpp
include .build/leonardo/src/weight.d







.build/leonardo/firmware.elf : .build/leonardo/src/weight.o .build/leonardo/HX711/libHX711.a .build/leonardo/arduino/libarduino.a
	@echo Linking firmware.elf
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega32u4 -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build/leonardo/firmware.hex : .build/leonardo/firmware.elf
	@echo Converting to firmware.hex
	@/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build/leonardo/src/dependencies.d .build/leonardo/arduino/dependencies.d .build/leonardo/HX711/dependencies.d

all : .build/leonardo/firmware.hex
	@true

